### ISSUE TITLE
"Directory 'dashboard/dist' does not exist"

### ISSUE THREAD

**Issue by Ilaprgg2** [khodedawsh/marzneshin#433]
I encounter "RuntimeError: Directory 'dashboard/dist' does not exist" when trying to install manually after running main.py

`Traceback (most recent call last):
  File "/root/Marzneshin/main.py", line 7, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/Marzneshin/app/marzneshin.py", line 124, in main
    StaticFiles(directory="dashboard/dist", html=True),
  File "/usr/local/lib/python3.10/dist-packages/starlette/staticfiles.py", line 59, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'dashboard/dist' does not exist`

**Comment by Ilaprgg2** [comment]
the solution was to run `npm run install && npm run build` in `marzneshin/dashboard/`

**Comment by khodedawsh** [comment]
try `make dashboard-deps && make dashboard-build` in project root directory after installing pnpm and npm.
